name: ermes-beta-test
favicon: null
layout_spectrum: 0.75078
typography_spectrum: 0.40047
title: Only a beta-test website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4dd1c'
    - '#ffffff'
    - '#b7e83f'
    - '#d0f081'
    - '#e2f4b8'
  brandStrength: 0.14551925542764366
  lightness: 0.5442040998023003
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
